### ISSUE TITLE
Lots of pages don't load

### ISSUE THREAD

**Issue by Silent-Hunter** [Corewala/Buran#33]
For some reason a lot of the known hosts on geminispace.info won't load. They do in another gemini browser (deedum).

Examples:
gemini://159.89.115.225
gemini://aaoth.xyz/visual

Potentially related, I can't get images to load either, and when I try to save the image using the three dot menu, it saves a corrupted file.

**Comment by mediocregopher** [comment]
@Corewala I believe this has to do with sites returning a `31` redirect to the same URL, but with a trailing slash. I was able to replicate @Silent-Hunter's issue on the `159.89.115.225` site, as well as my own site, `gemini://mediocregopher.com`.

If you type `gemini://mediocregopher.com` into Buran v1.12 it just hangs, but `gemini://mediocregopher.com/` works fine. If I do the request manually, I see that a 31 is getting returned:

```
# echo 'gemini://mediocregopher.com' | ncat -C --ssl mediocregopher.com 1965
31 gemini://mediocregopher.com/
```

Similarly with `159.89.115.225`, trying `gemini://159.89.115.225/` in Buran does indeed work, but without the trailing slash doesn't:
```
# echo 'gemini://159.89.115.225' | ncat -C --ssl 159.89.115.225 1965
31 gemini://159.89.115.225/
```

Doing the ncat with the aaoth.xyz url doesn't return anything for me, but adding the trailing slash in Buran does fix it as well, so I'm not 100% sure what's going on there. But anyway, it seems like 31 redirects might have some kind of bug.

**Comment by Corewala** [comment]
Thank you so much for the information @mediocregopher! I haven't been working on this project a whole lot, so this might be a good bug for me to get back into it.

I'm not sure what's going on with images for you @Silent-Hunter, since I haven't run into any issue on this end yet. Do you have any more details or examples of specific images which break?

**Comment by Silent-Hunter** [comment]
Sure! "gemini://158.nu/images/full/imitation/2021-06-30-0024.jpg" doesn't work. Also the page that that is linked from, "gemini://158.nu/imitation.gmi", spits out tons of errors as well.
![Screenshot_20230129-105039](https://user-images.githubusercontent.com/3732535/215349089-80be5da3-7525-400c-94c2-c4af2428ca05.png)
![Screenshot_20230129-105020](https://user-images.githubusercontent.com/3732535/215349097-17fbca09-144b-456c-a541-7b905129cb86.png)

**Comment by Silent-Hunter** [comment]
Oh and pasting in the image URL directly doesn't error, but it goes to a blank page that just says "Image" at the top.

**Comment by Corewala** [comment]
[73afc7c](https://github.com/Corewala/Buran/commit/73afc7c684b9983f87aa19f954ef6ce1df99360f) should take care of the hanging redirect problem. The way that Buran deals with concurrent responses is that only the response from the most recent request is handled, but my implementation would occasionally cause the "current request" value to be reset in between the time that the redirect was processed and the response was handled, meaning that it would drop the response as though there was a more recent request.

@Silent-Hunter I'm going to move the image bug to another issue, since it doesn't really seem to be related to redirects.
